### ISSUE TITLE
Nextflow AIO cloudformation stack gets rolled back

### ISSUE THREAD

**Issue by rspreafico-vir** [aws-samples/aws-genomics-workflows#18] opened 2019-04-03 19:24 UTC
Hi there, I tried to run the nextflow resources stack (which worked) and the AIO stack (which got rolled back). This is a tremendous and super-useful resource: would it be possible to get that fixed? 

Also, would it be possible to clearly document which steps are NOT covered by the AIO stack? For example, building and publishing the Docker container to ECR needs to be done separately.

**Comment by wleepang** [comment] 2019-04-04 04:29
@rspreafico-vir - I was able to get a rollback from CloudFormation on this stack.  The cause for me was when a single bucket is used, the fact that it already exists (created previously by the `s3` stack) by the time the `nextflow-resources` stack is run is not passed on correctly.

I've created a patch in #19 

Can you confirm that this was your issue as well?  You can check via the "Events" tab for the "NextflowStack" sub-stack.

**Comment by rspreafico-vir** [comment] 2019-04-04 16:22
Thanks @wleepang for the fast response and resolution. Here is the error I got running my stack (as admin):

```
The following resource(s) failed to create: [S3NextflowBucket, IAMNextflowJobRole].
```

**Comment by rspreafico-vir** [comment] 2019-04-04 16:26
More generally, the docs for running Nextflow with AWS batch are a great resource. Would you be open to some feedback on that? Along the same lines, what are the membership rules in this repo (e.g. for external contributions from Nextflow developers or third parties?)

**Comment by rspreafico-vir** [comment] 2019-04-04 18:04
Still a rollback:

```
The following resource(s) failed to create: [S3NextflowBucket]
```

**Comment by rspreafico-vir** [comment] 2019-04-04 18:05
Never mind, I just saw the PR has not been merged yet

**Comment by wleepang** [comment] 2019-04-04 19:03
@wleepang - just merged the pr, should be a couple minutes for it to build and deploy.

Re: contributions - totally open to having external feedback / contributions!  Just submit a PR for anything you want to add.

**Closed by wleepang** 2019-04-04 19:03 UTC
